### ISSUE TITLE
Add: page to demonstrate survey embed

### ISSUE THREAD

**Issue by juliekdang** [DCgov/Community-Engagement-Program#7]
create a page with the proto branding that embeds an iframe with  src="https://forms.beta.dc.gov/s3/SpeakUpDCHousing2"

This frame should... 
- enable the full functionality of the surveygizmo form.
- be as responsive as possible
- have full page view capability

Navigation
- link back to splash
- link from survey link and button on splash

starting reference:
- https://getbootstrap.com/docs/4.1/utilities/embed/

**Comment by unlockedSound** [comment]
to confirm, this is to be a new page (linked to it?)

Do we effectively want the iframe to not have vertical scroll inside it?

**Comment by juliekdang** [comment]
yes, new page with a link back to the splash. 

scroll is fine, probably unavoidable

**Comment by juliekdang** [comment]
oh and forgot to mention: I tested it yesterday and verified that surveygizmo allows it.

**Comment by unlockedSound** [comment]
page pushed, awaiting confirmation that it's good before closing

**Comment by unlockedSound** [comment]
@juliekdang 

please try the survey on your mobile android device. Should work now.
https://open.dc.gov/Community-Engagement-Program/splash-page/survey.html

**Comment by juliekdang** [comment]
It works to display the keyboard but the cost is the survey navigation is now offscreen. Keyboard vs. navigation is too much of a sophie's choice 😢  - we need both... 

![image](https://user-images.githubusercontent.com/4007899/42379451-b0a46514-80f8-11e8-88a6-5c50ddc654fa.png)

**Comment by unlockedSound** [comment]
@juliekdang 

I'm not clear that you can honestly get both.

Have you tried testing the survey through to the later longer pages? I'd like to confirm if those even work being the later pages are over double the length of the first two pages and I'm not clear if those will even work on android due to text boxes being low on the page, the y-overflow issues, etc.

Before I attempt to reduce the page height could you confirm if these are actually 'fixed'?

**Comment by juliekdang** [comment]
Per @unlockedSound, requesting that we change the setting one-per-page on mobile

Reference:
https://help.surveygizmo.com/help/survey-interactions
